version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  apt_packages:
    - portaudio19-dev
    - libsndfile1-dev
    - libportmidi-dev
    - liblo-dev

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
